### PR TITLE
Contact form post route

### PR DESCRIPTION
**Pull request by pankajpawar2**
Added routes, model and controller for creating new contact.
Also, added GET route which can be accessed only from admin dashboard, to get list of all the contacts
Please check and let me know

### CODE REVIEW

**Comment by LevPewPew** [comment]
hey since you wern't able to make it to team meeting today i'll paste here what the fields should be as per my earlier comment:

```js
name
mobile
eventDate
serviceType
totalPeopleJustMakeup
totalPeopleWithHair
timeToFinish
applicationAddress
howDidYouHear
addedQuestionsOrInfo
```
let me know if you have any questions

**Comment by pankajpawar2** [comment]
Added required fields to the contact model as requested. 
@LevPewPew Could you please check and let me know if it looks allright.
Thanks mate

**Comment by pankajpawar2** [comment]
@LevPewPew  ahhhh silly me. Just changed it now. Check it when u can. thanks

**Comment by LevPewPew** [comment]
yep sweet, merged, thnx

**Pull request merged**
